package com.fpera.mindmatch.utils

import com.fpera.mindmatch.R

const val EXTRA_GAME_NAME = "EXTRA_GAME_NAME"
const val EXTRA_BOARD_SIZE = "EXTRA_BOARD_SIZE"
val DEFAULT_ICONS = listOf(
  R.drawable.ic_face,
  R.drawable.ic_flower,
  R.drawable.ic_gift,
  R.drawable.ic_heart,
  R.drawable.ic_home,
  R.drawable.ic_lightning,
  R.drawable.ic_moon,
  R.drawable.ic_plane,
  R.drawable.ic_school,
  R.drawable.ic_send,
  R.drawable.ic_star,
  R.drawable.ic_work,
  R.drawable.ic_basketball,
  R.drawable.ic_drive,
  R.drawable.ic_fingerprints,
  R.drawable.ic_videogames,
  R.drawable.ic_football,
  R.drawable.ic_esports,
  R.drawable.ic_tag,
  R.drawable.ic_whatshot,
  R.drawable.ic_thermostat,
  R.drawable.ic_smarttoy,
  R.drawable.ic_pets,
  R.drawable.ic_pest,
  R.drawable.ic_android,
  R.drawable.ic_cake,
  R.drawable.ic_camera,
  R.drawable.ic_child,
  R.drawable.ic_celebration,
  R.drawable.ic_pokemon,
  R.drawable.ic_hands,
  R.drawable.ic_construction,
  R.drawable.ic_games,
  R.drawable.ic_grass,
  R.drawable.ic_icecream,
  R.drawable.ic_hottub,
  R.drawable.ic_emoticon,
  R.drawable.ic_language,
  R.drawable.ic_pizza,
  R.drawable.ic_tungsten,
  R.drawable.ic_twowheeler,
  R.drawable.ic_viewin,
  R.drawable.ic_verified,
  R.drawable.ic_wifi,
  R.drawable.ic_voicemail,
  R.drawable.ic_umbrella,
  R.drawable.ic_sync,
  R.drawable.ic_superscript,
  R.drawable.ic_motorsports,
  R.drawable.ic_mma,
  R.drawable.ic_rodent,
  R.drawable.ic_palette,
  R.drawable.ic_outlet,
  R.drawable.ic_hourglass,
  R.drawable.ic_lock
)